-- Esquema inicial CROSAIM para Supabase. Para una base ya creada,
-- ejecutar también supabase_migration_application_state.sql.
create extension if not exists pgcrypto;

create table if not exists public.postulaciones (
  id uuid primary key default gen_random_uuid(),
  nombre text not null,
  discord_id text,
  discord_username text,
  rol text,
  rango text,
  region text,
  descripcion text,
  foto_url text,
  estado text not null default 'POSTULACIÓN'
    check (estado in ('POSTULACIÓN', 'REVISIÓN', 'ENTREVISTA', 'APROBADA', 'RECHAZADA', 'ROSTER', 'TRYOUT')),
  motivo_rechazo text,
  discord_webhook_id text,
  discord_postulacion_message_id text,
  discord_revision_message_id text,
  discord_aprobacion_message_id text,
  revisado_por_discord_id text,
  state_changed_by_discord_id text,
  state_changed_by_type text,
  state_changed_at timestamptz not null default now(),
  interview_at timestamptz,
  approved_at timestamptz,
  rejected_at timestamptz,
  roster_at timestamptz,
  tryout_at timestamptz,
  payload_original jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  reviewed_at timestamptz
);

create table if not exists public.postulaciones_auditoria (
  id bigint generated by default as identity primary key,
  postulación_id uuid not null references public.postulaciones(id) on delete cascade,
  evento_id uuid not null default gen_random_uuid() unique,
  estado_anterior text,
  estado_nuevo text not null,
  actor_discord_id text,
  actor_tipo text not null default 'bot',
  fuente text not null default 'discord',
  detalle jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists postulaciones_estado_idx on public.postulaciones (estado);
create index if not exists postulaciones_discord_id_idx on public.postulaciones (discord_id);
create index if not exists postulaciones_created_at_idx on public.postulaciones (created_at desc);
create index if not exists postulaciones_auditoria_postulacion_created_idx on public.postulaciones_auditoria (postulación_id, created_at desc);
-- Idempotencia: un mismo mensaje de Discord solo puede crear una postulación.
create unique index if not exists postulaciones_discord_message_unique_idx
  on public.postulaciones (discord_postulacion_message_id)
  where discord_postulacion_message_id is not null;

alter table public.postulaciones enable row level security;
alter table public.postulaciones_auditoria enable row level security;

-- El bot usa SUPABASE_SERVICE_ROLE_KEY únicamente en el servidor y no necesita
-- una policy pública. No expongas esa clave en navegador, GitHub ni logs.
