-- CROSAIM: perfiles Manus + vínculo Discord + cola de eventos.
-- Ejecutar en Supabase SQL Editor después de revisar las tablas actuales de la web.
-- Este archivo es una migración versionada; no contiene secretos.

create extension if not exists pgcrypto;

create table if not exists public.player_profiles (
  id uuid primary key default gen_random_uuid(),
  manus_user_id text not null unique,
  display_name text not null,
  photo_url text,
  role text,
  secondary_roles jsonb not null default '[]'::jsonb,
  rank text,
  peak_rank text,
  region text,
  availability text,
  bio text,
  socials jsonb not null default '{}'::jsonb,
  profile_version integer not null default 1 check (profile_version > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.player_discord_accounts (
  manus_user_id text primary key references public.player_profiles(manus_user_id) on delete cascade,
  discord_id text not null unique,
  discord_username text,
  avatar_url text,
  connected_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.discord_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  idempotency_key text not null unique,
  payload jsonb not null,
  status text not null default 'pending'
    check (status in ('pending', 'processing', 'delivered', 'failed')),
  attempts integer not null default 0 check (attempts >= 0),
  last_error text,
  delivered_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists player_profiles_updated_at_idx
  on public.player_profiles (updated_at desc);
create index if not exists discord_events_pending_idx
  on public.discord_events (status, created_at)
  where status in ('pending', 'failed');

-- RLS protege las tablas frente al cliente. Las escrituras del bot usan service role.
alter table public.player_profiles enable row level security;
alter table public.player_discord_accounts enable row level security;
alter table public.discord_events enable row level security;

-- No crear policies públicas automáticamente en esta migración.
-- La web debe añadir policies específicas basadas en su sistema Manus OAuth.
-- Nunca expongas SUPABASE_SERVICE_ROLE_KEY al navegador.
