-- CROSAIM: migración segura desde el esquema inicial de postulaciones.
-- Ejecutar una vez en Supabase SQL Editor antes de desplegar el bot actualizado.

alter table public.postulaciones
  add column if not exists updated_at timestamptz not null default now(),
  add column if not exists state_changed_at timestamptz not null default now(),
  add column if not exists state_changed_by_discord_id text,
  add column if not exists state_changed_by_type text,
  add column if not exists interview_at timestamptz,
  add column if not exists approved_at timestamptz,
  add column if not exists rejected_at timestamptz,
  add column if not exists roster_at timestamptz,
  add column if not exists tryout_at timestamptz;

update public.postulaciones
set estado = case lower(estado)
  when 'pendiente' then 'POSTULACIÓN'
  when 'revision' then 'REVISIÓN'
  when 'revisión' then 'REVISIÓN'
  when 'entrevista' then 'ENTREVISTA'
  when 'aprobada' then 'APROBADA'
  when 'rechazada' then 'RECHAZADA'
  when 'roster' then 'ROSTER'
  when 'tryout' then 'TRYOUT'
  else 'POSTULACIÓN'
end;

alter table public.postulaciones drop constraint if exists postulaciones_estado_check;
alter table public.postulaciones
  add constraint postulaciones_estado_check
  check (estado in ('POSTULACIÓN', 'REVISIÓN', 'ENTREVISTA', 'APROBADA', 'RECHAZADA', 'ROSTER', 'TRYOUT'));

create table if not exists public.postulaciones_auditoria (
  id bigint generated by default as identity primary key,
  postulación_id uuid not null references public.postulaciones(id) on delete cascade,
  evento_id uuid not null default gen_random_uuid() unique,
  estado_anterior text,
  estado_nuevo text not null,
  actor_discord_id text,
  actor_tipo text not null default 'bot',
  fuente text not null default 'discord',
  detalle jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists postulaciones_auditoria_postulacion_created_idx
  on public.postulaciones_auditoria (postulación_id, created_at desc);
create index if not exists postulaciones_estado_changed_idx
  on public.postulaciones (estado, state_changed_at desc);

create or replace function public.crosaim_touch_postulacion()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists crosaim_postulacion_updated_at on public.postulaciones;
create trigger crosaim_postulacion_updated_at
before update on public.postulaciones
for each row execute function public.crosaim_touch_postulacion();

alter table public.postulaciones_auditoria enable row level security;
-- El bot usa la service role solo en servidor. No crear policies públicas.
